#!/usr/bin/env php

# Build the image "sepiphy/laravel_testing_composer"
docker build ./src/composer -t sepiphy/laravel_testing_composer

# Build the image "sepiphy/laravel_testing_php7.1"
docker build ./src/php7.1 -t sepiphy/laravel_testing_php7.1

# Build the image "sepiphy/laravel_testing_php7.2"
docker build ./src/php7.2 -t sepiphy/laravel_testing_php7.2

# Build the image "sepiphy/laravel_testing_php7.3"
docker build ./src/php7.3 -t sepiphy/laravel_testing_php7.3
