version: "3.3"

networks:
  lttnet:
    driver: bridge

services:
  memcached:
    image: ltt-memcached1.5:latest
    build:
      context: ./docker/memcached1.5
    networks:
      - lttnet

  redis:
    image: ltt-redis5.0:latest
    build:
      context: ./docker/redis5.0
    networks:
      - lttnet

  mysql:
    image: ltt-mysql5.7:latest
    build:
      context: ./docker/mysql5.7
    networks:
      - lttnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    command: --default-authentication-plugin=mysql_native_password

  php7.2:
    image: ltt-php7.2:latest
    build:
      context: ./docker/php7.2
      args:
        - CODE_GID=${CODE_GID}
        - CODE_UID=${CODE_UID}
    volumes:
      - ${LARAVEL_FRAMEWORK_DIR}:/app
      - $PWD/phpunit.xml:/app/phpunit.xml
    command: php -S localhost:8080
    networks:
      - lttnet
