version: "3.3"

networks:
  lttnet:
    driver: bridge

services:
  memcached:
    image: ltt-memcached${MEMCACHED_VERSION}:latest
    build:
      context: ./docker/memcached/${MEMCACHED_VERSION}
    networks:
      - lttnet

  redis:
    image: ltt-redis${REDIS_VERSION}:latest
    build:
      context: ./docker/redis/${REDIS_VERSION}
    networks:
      - lttnet

  mysql:
    image: ltt-mysql${MYSQL_VERSION}:latest
    build:
      context: ./docker/mysql/${MYSQL_VERSION}
    networks:
      - lttnet
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
    command: --default-authentication-plugin=mysql_native_password

  php:
    image: ltt-php${PHP_VERSION}:latest
    build:
      context: ./docker/php/${PHP_VERSION}
      args:
        - CODE_GID=${CODE_GID}
        - CODE_UID=${CODE_UID}
    command: php -S localhost:8080
    volumes:
      - $PWD/storage/composer:/home/php/.composer
      - ${REPOSITORY}:/app/repository
    networks:
      - lttnet
    environment:
      - DB_CONNECTION=mysql
      - DB_DATABASE=laravel
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MEMCACHED_HOST=memcached
      - MEMCACHED_PORT=11211
