#!/usr/bin/env bash

LARAVEL_PHP_VERSION="$1_testing"
DOCKER_IMAGE="$LARAVEL_PHP_VERSION"

echo "Testing Laravel Framework [$LARAVEL_PHP_VERSION]"
echo # Add an empty line.

echo '>>> Framework cloning...'
if [ ! -d "$PWD/framework" ]; then
    git clone git@github.com:laravel/framework.git
fi
echo # Add an empty line.

echo '>>> PHPUnit testing...'
docker run -it --rm \
    -v "$PWD/framework":/usr/src/framework \
    -v "$PWD/runtest":/usr/src/framework/runtest \
    -v "$PWD/phpunit.xml":/usr/src/framework/phpunit.xml \
    -w /usr/src/framework \
    -u $(id -u ${USER}):$(id -g ${USER}) \
    --rm \
    --network laravel_testing_network \
    "sepiphy/$LARAVEL_PHP_VERSION" \
    /bin/bash runtest
echo # Add an empty line.

echo '>>> Framework removing...'
rm -rf framework
echo # Add an empty line.
